/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/consulting': typeof ConsultingRoute
  '/contacts': typeof ContactsRoute
  '/games': typeof GamesRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/consulting': typeof ConsultingRoute
  '/contacts': typeof ContactsRoute
  '/games': typeof GamesRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/consulting': typeof ConsultingRoute
  '/contacts': typeof ContactsRoute
  '/games': typeof GamesRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/apps'
    | '/consulting'
    | '/contacts'
    | '/games'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/apps'
    | '/consulting'
    | '/contacts'
    | '/games'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/apps'
    | '/consulting'
    | '/contacts'
    | '/games'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AppsRoute: typeof AppsRoute
  ConsultingRoute: typeof ConsultingRoute
  ContactsRoute: typeof ContactsRoute
  GamesRoute: typeof GamesRoute
  OfertaRoute: typeof OfertaRoute
  PrivacyRoute: typeof PrivacyRoute
  SitesRoute: typeof SitesRoute
  SystemsRoute: typeof SystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AppsRoute: AppsRoute,
  ConsultingRoute: ConsultingRoute,
  ContactsRoute: ContactsRoute,
  GamesRoute: GamesRoute,
  OfertaRoute: OfertaRoute,
  PrivacyRoute: PrivacyRoute,
  SitesRoute: SitesRoute,
  SystemsRoute: SystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
