/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as MiniAppsRouteImport } from './routes/mini-apps'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as BotsAiRouteImport } from './routes/bots-ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'

const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniAppsRoute = MiniAppsRouteImport.update({
  id: '/mini-apps',
  path: '/mini-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsAiRoute = BotsAiRouteImport.update({
  id: '/bots-ai',
  path: '/bots-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots-ai': typeof BotsAiRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/mini-apps': typeof MiniAppsRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots-ai': typeof BotsAiRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/mini-apps': typeof MiniAppsRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots-ai': typeof BotsAiRoute
  '/cases': typeof CasesRoute
  '/contacts': typeof ContactsRoute
  '/mini-apps': typeof MiniAppsRoute
  '/oferta': typeof OfertaRoute
  '/privacy': typeof PrivacyRoute
  '/sites': typeof SitesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots-ai'
    | '/cases'
    | '/contacts'
    | '/mini-apps'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots-ai'
    | '/cases'
    | '/contacts'
    | '/mini-apps'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/articles/$slug'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/bots-ai'
    | '/cases'
    | '/contacts'
    | '/mini-apps'
    | '/oferta'
    | '/privacy'
    | '/sites'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsAiRoute: typeof BotsAiRoute
  CasesRoute: typeof CasesRoute
  ContactsRoute: typeof ContactsRoute
  MiniAppsRoute: typeof MiniAppsRoute
  OfertaRoute: typeof OfertaRoute
  PrivacyRoute: typeof PrivacyRoute
  SitesRoute: typeof SitesRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-apps': {
      id: '/mini-apps'
      path: '/mini-apps'
      fullPath: '/mini-apps'
      preLoaderRoute: typeof MiniAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots-ai': {
      id: '/bots-ai'
      path: '/bots-ai'
      fullPath: '/bots-ai'
      preLoaderRoute: typeof BotsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsAiRoute: BotsAiRoute,
  CasesRoute: CasesRoute,
  ContactsRoute: ContactsRoute,
  MiniAppsRoute: MiniAppsRoute,
  OfertaRoute: OfertaRoute,
  PrivacyRoute: PrivacyRoute,
  SitesRoute: SitesRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
